### ISSUE TITLE
Hardcore/Softcore and Ladder/Non-Ladder filters are not functional

### ISSUE THREAD

**Issue by DimitreBogdanov** [metalclaw/D2DCloneStatus#1]
When trying to filter down by Hardcore/Softcore or by Ladder/Non-Ladder it doesn't actually filter down based on the input provided

**Comment by DimitreBogdanov** [comment]
Lines 104 and 109 in Form1.cs are using the region filter instead of the ladder/non-ladder and hc/sc filters, the code should be set to:
```                //ladder/non-ladder filtering
                if (cbFilterLadderNonLadder.SelectedIndex != 0 && res.ladder != cbFilterLadderNonLadder.SelectedIndex)
                {
                    return false;
                }
                //hc/sc filtering
                if (cbFilterHCSC.SelectedIndex != 0 && res.hc != cbFilterHCSC.SelectedIndex)
                {
                    return false;
                }
```
With those changes it seems to be working fine

**Comment by metalclaw** [comment]
A classic copy/paste error :D It's fixed now. Thanks, and good catch!
